package com.moraramee.cocktail.platform.type;

import java.util.HashSet;
import java.util.Set;

public enum IngredientCategory {
	SPIRIT(null), // rum, whiskey, gin ... (base)
		VODKA(SPIRIT),
			VODKA_PEACH(VODKA),
			VODKA_LEMON(VODKA),
		RUM(SPIRIT),
			RUM_GOLD(RUM),
			RUM_WHITE(RUM),
			RUM_DARK(RUM),
			RUM_OVER_PROOF(RUM),
		GIN(SPIRIT),
			GIN_GENEVER(GIN),
			GIN_OLD_TOM(GIN),
			GIN_LONDON_DRY(GIN),
			GIN_SLOE(GIN),
		WHISKEY(SPIRIT),
			WHISKEY_IRISH(WHISKEY),
			WHISKEY_AMERICAN(WHISKEY),
				WHISKEY_BOURBON(WHISKEY_AMERICAN),
				WHISKEY_CORN(WHISKEY_AMERICAN),
				WHISKEY_RYE(WHISKEY_AMERICAN),
				WHISKEY_TENNESSEE(WHISKEY_AMERICAN),
			WHISKEY_SCOTCH(WHISKEY),
				WHISKEY_BLENDED(WHISKEY_SCOTCH),
				WHISKEY_SINGLE_MALT(WHISKEY_SCOTCH),
		BRANDY(SPIRIT),
			BRANDY_EAU_DE_VIE(BRANDY),
			BRANDY_FRENCH(BRANDY),
				BRANDY_COGNAC(BRANDY_FRENCH),
				BRANDY_ARMAGNAC(BRANDY_FRENCH),
			BRANDY_ARMENIA(BRANDY),
			BRANDY_JEREZ(BRANDY),
			BRANDY_PISCO(BRANDY),
			BRANDY_POMACE(BRANDY),
			BRANDY_APPLE(BRANDY),
			BRANDY_KIRSCH(BRANDY),
		TEQUILA(SPIRIT),
			TEQUILA_BLANCO(TEQUILA),
			TEQUILA_REPOSADO(TEQUILA),
			TEQUILA_ANEJO(TEQUILA),
	LIQUEUR(null), // apple liq, orange liq ...
		LIQUEUR_ORANGE(LIQUEUR),
			LIQUEUR_CURACAO(LIQUEUR_ORANGE),
			LIQUEUR_BLUE_CURACAO(LIQUEUR_ORANGE),
			LIQUEUR_TRIPLE_SEC(LIQUEUR_ORANGE),
			LIQUEUR_COINTREAU(LIQUEUR_ORANGE),
		LIQUEUR_BLACK_CURRENT(LIQUEUR),
			LIQUEUR_CREME_DE_CASSIS(LIQUEUR_BLACK_CURRENT),
		LIQUEUR_MELON(LIQUEUR),
			LIQUEUR_MIDORI(LIQUEUR_MELON),
		LIQUEUR_BANANA(LIQUEUR),
			LIQUEUR_CREME_DE_BANANA(LIQUEUR_BANANA),
		LIQUEUR_CACAO(LIQUEUR),
			LIQUEUR_CREME_DE_CACAO_WHITE(LIQUEUR_CACAO),
			LIQUEUR_CREME_DE_CACAO_BROWN(LIQUEUR_CACAO),
		LIQUEUR_MINT(LIQUEUR),
			LIQUEUR_CREME_DE_MINT_WHITE(LIQUEUR_MINT),
			LIQUEUR_CREME_DE_MINT_GREEN(LIQUEUR_MINT),
		LIQUEUR_APPLE(LIQUEUR),
		LIQUEUR_PEACH(LIQUEUR),
		LIQUEUR_BITTERS(LIQUEUR),
			LIQUEUR_BITTERS_CAMPARI(LIQUEUR_BITTERS),
			LIQUEUR_BITTERS_APEROL(LIQUEUR_BITTERS),
			LIQUEUR_BITTERS_SUZU(LIQUEUR_BITTERS),
			LIQUEUR_BITTERS_CHARTREUSE(LIQUEUR_BITTERS),
			LIQUEUR_BITTERS_JAGER_MEISTER(LIQUEUR_BITTERS),

	WINE(null), // champagne
		WINE_RED(WINE),
			WINE_RED_SWEET(WINE_RED),
			WINE_RED_DRY(WINE_RED),
		WINE_WHITE(WINE),
			WINE_WHITE_SWEET(WINE_WHITE),
			WINE_WHITE_DRY(WINE_WHITE),
		WINE_ROSE(WINE),
			WINE_ROSE_SWEET(WINE_ROSE),
			WINE_ROSE_DRY(WINE_ROSE),
		WINE_SPARKLING(WINE),
			WINE_SPARKLING_RED(WINE_SPARKLING),
			WINE_SPARKLING_WHITE(WINE_SPARKLING),
			WINE_SPARKLING_ROSE(WINE_SPARKLING),

	BEER(null),
		BEER_COMMON(BEER),
		BEER_DARK(BEER),
	JUICE(null), // apple juice, orange juice ...
	BEVERAGE(null), // cola, soda water, milk ...
		BEVERAGE_SODA_WATER(BEVERAGE),
	MIXER(null),
		MIXER_ICE(MIXER), // crushed ice, ice ...
		MIXER_HERB(MIXER), // apple mint, pepper mint ...
		MIXER_SYRUP(MIXER), // grenadine syrup, honey ...
		MIXER_PANTRY(MIXER), // eggs,
		MIXER_FRUIT(MIXER),
	GARNISH(null),// orange peel, lemon twist ...
		GARNISH_PEEL(GARNISH),
		GARNISH_TWIST(GARNISH),
		GARNISH_FRUIT(GARNISH)
	;

	private IngredientCategory parent;
	private Set<IngredientCategory> children = new HashSet<>();

	IngredientCategory(IngredientCategory parent) {
		this.parent = parent;
		if (this.parent != null) {
			this.parent.addChild(this);
		}
	}

	private void addChild(IngredientCategory child) {
		for (IngredientCategory c = this; c != null; c = c.parent) {
			c.children.add(child);
		}
	}
}
